# Generated by Django 4.0.6 on 2022-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(default='', max_length=25),
        ),
    ]
