# Generated by Django 4.0.6 on 2022-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_laboratorio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('DISCENTE', 'Discente'), ('TECNICO', 'Técnico')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero_cracha',
            field=models.CharField(max_length=25, verbose_name='Número do crachá'),
        ),
    ]
