# Generated by Django 4.0.6 on 2022-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_laboratorio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='nome_lab',
            field=models.CharField(max_length=256, verbose_name='Nome do Laboratório'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(default='', max_length=25, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero_cracha',
            field=models.CharField(max_length=25, verbose_name='Número do Crachá'),
        ),
    ]
