# Generated by Django 4.0.6 on 2022-08-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_laboratorio_nome_lab_alter_pessoa_funcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('DISCENTE', 'Discente'), ('TECNICO', 'Técnico')], default='None', max_length=25, verbose_name='Função'),
        ),
    ]
