# Generated by Django 4.0.6 on 2022-08-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_pessoa_funcao_alter_pessoa_numero_cracha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('DISCENTE', 'Discente'), ('TECNICO', 'Técnico')], default=None, max_length=25),
        ),
    ]
