# Generated by Django 4.0.6 on 2022-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_alter_pessoa_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Discente', 'Discente'), ('Técnico', 'Técnico')], default='None', max_length=25, verbose_name='Função'),
        ),
    ]
