# Generated by Django 4.0.6 on 2022-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_pessoa_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('', 'Escolha sua função'), ('Docente', 'Docente'), ('Discente', 'Discente'), ('Técnico', 'Técnico'), ('Pesquisador', 'Pesquisador')], default='None', max_length=25, verbose_name='Função'),
        ),
    ]
