# Generated by Django 4.0.6 on 2022-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_alter_pessoa_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ramal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ramal'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sala',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero_cracha',
            field=models.IntegerField(max_length=25, verbose_name='Número do Crachá'),
        ),
    ]
