# Generated by Django 4.0.6 on 2022-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_pessoa_ramal_pessoa_sala_alter_pessoa_numero_cracha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero_cracha',
            field=models.IntegerField(verbose_name='Número do Crachá'),
        ),
    ]
