# Generated by Django 4.0.6 on 2022-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_pessoa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bolsista',
            field=models.CharField(choices=[('', 'Selecione uma opção!'), ('Não', 'Não'), ('Aluno Bolsista', 'Aluno Bolsista'), ('Professor Bolsista (1A)', 'Professor Bolsista (1A)'), ('Professor Bolsista (1B)', 'Professor Bolsista (1B)'), ('Professor Bolsista (1C)', 'Professor Bolsista (1C)'), ('Professor Bolsista (1D)', 'Professor Bolsista (1D)'), ('Professor Bolsista (2)', 'Professor Bolsista (2)'), ('Professor Bolsista (SR))', 'Professor Bolsista (SR)')], default='None', max_length=50, verbose_name='É Bolsista?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('', 'Selecione uma opção'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='None', max_length=25, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('', 'Selecione sua função'), ('Servidor Docente', 'Servidor Docente'), ('Servidor Técnico', 'Servidor Técnico'), ('Técnico Terceirizado', 'Técnico Terceirizado'), ('Discente Graduação', 'Discente Graduação'), ('Discente Mestrado', 'Discente Mestrado'), ('Discente Doutorado', 'Discente Doutorado'), ('Discente Pós-Doutorado', 'Discente Pós-Doutorado'), ('Outro', 'Outro')], default='None', max_length=25, verbose_name='Função'),
        ),
    ]
